### ISSUE TITLE
STEP File

### ISSUE THREAD

**Issue by smooshworx** [richardjm/voron-parts#2]
Is it possible to have the STEP file added for each release for those of us that do not use Fusion? Either way thanks for this awesome design

**Comment by richardjm** [comment]
For which design?

**Comment by ZESTE-FR** [comment]
for FilamentLatch, I want to modify it for 2020 extrusion with a groove of 5mm

**Comment by richardjm** [comment]
https://github.com/richardjm/voron-parts/blob/main/voron-2.4/FilamentLatch/CAD/NewLatch%20v108.step Enjoy
