### ISSUE TITLE
New Latch Main Sketch Error when changing Panel Depth

### ISSUE THREAD

**Issue by ChaosBlades** [richardjm/voron-parts#3]
I am getting a Main Sketch error when I try to change the panel depth in CAD. Does not matter what I change it to. Can you check? May be some update to Fusion 360 that is causing issues.

**Comment by richardjm** [comment]
You're not wrong. Looks like some update they've made has made the sketch not resolve dimensions correctly.

What size were you aiming for?

**Comment by richardjm** [comment]
I've reworked the sketch. The design has limits from about 3 to 8.5mm.
