### ISSUE TITLE
@richardjm - STEP Version of latch

### ISSUE THREAD

**Issue by ZESTE-FR** [richardjm/voron-parts#4]
Hi, 

Can you upload a step version of the voron 2.4 latch ? I only work with freecad and I want to adapt it for a aluminum profile 2020 with a groove of 5mm.

BR

**Comment by richardjm** [comment]
https://github.com/richardjm/voron-parts/blob/main/voron-2.4/FilamentLatch/CAD/NewLatch%20v108.step Enjoy
